import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface DailySummary {
  date: string;
  totalRevenue: number;
  totalOrders: number;
  avgOrderValue: number;
  topItems: Array<{ name: string; count: number }>;
  paymentBreakdown: Record<string, number>;
  peakHour: number;
}

async function generateDailySummary(supabase: any, date: Date): Promise<DailySummary> {
  const startOfDay = new Date(date);
  startOfDay.setHours(0, 0, 0, 0);
  
  const endOfDay = new Date(date);
  endOfDay.setHours(23, 59, 59, 999);

  // Get all orders for the day
  const { data: orders, error } = await supabase
    .from("orders")
    .select("id, total, payment_method, created_at, order_items(*)")
    .gte("created_at", startOfDay.toISOString())
    .lte("created_at", endOfDay.toISOString())
    .in("status", ["delivered", "ready", "preparing"]);

  if (error) throw error;

  if (!orders || orders.length === 0) {
    return {
      date: date.toISOString().split("T")[0],
      totalRevenue: 0,
      totalOrders: 0,
      avgOrderValue: 0,
      topItems: [],
      paymentBreakdown: {},
      peakHour: 12,
    };
  }

  // Calculate totals
  const totalRevenue = orders.reduce((sum: number, o: any) => sum + (o.total || 0), 0);
  const totalOrders = orders.length;
  const avgOrderValue = Math.round(totalRevenue / totalOrders);

  // Payment breakdown
  const paymentBreakdown: Record<string, number> = {};
  orders.forEach((o: any) => {
    const method = o.payment_method || "unknown";
    paymentBreakdown[method] = (paymentBreakdown[method] || 0) + 1;
  });

  // Top items
  const itemCounts: Record<string, number> = {};
  orders.forEach((o: any) => {
    (o.order_items || []).forEach((item: any) => {
      const name = item.sauce_name || item.side_dish || "Unknown";
      itemCounts[name] = (itemCounts[name] || 0) + item.quantity;
    });
  });
  const topItems = Object.entries(itemCounts)
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 5);

  // Peak hour
  const hourCounts: Record<number, number> = {};
  orders.forEach((o: any) => {
    const hour = new Date(o.created_at).getHours();
    hourCounts[hour] = (hourCounts[hour] || 0) + 1;
  });
  const peakHour = Object.entries(hourCounts)
    .sort((a, b) => b[1] - a[1])[0]?.[0] || "12";

  return {
    date: date.toISOString().split("T")[0],
    totalRevenue,
    totalOrders,
    avgOrderValue,
    topItems,
    paymentBreakdown,
    peakHour: parseInt(peakHour),
  };
}

function formatSummaryMessage(summary: DailySummary): string {
  const formatPrice = (amount: number) => 
    `UGX ${amount.toLocaleString()}`;

  const paymentLines = Object.entries(summary.paymentBreakdown)
    .map(([method, count]) => `  • ${method}: ${count} orders`)
    .join("\n");

  const topItemsLines = summary.topItems
    .map((item, i) => `  ${i + 1}. ${item.name} (${item.count}x)`)
    .join("\n");

  return `📊 *9Yards Daily Sales Summary*
📅 ${summary.date}

💰 *Revenue*: ${formatPrice(summary.totalRevenue)}
📦 *Orders*: ${summary.totalOrders}
📈 *Avg Order*: ${formatPrice(summary.avgOrderValue)}

💳 *Payment Methods*
${paymentLines || "  No orders"}

🏆 *Top Items*
${topItemsLines || "  No items"}

⏰ *Peak Hour*: ${summary.peakHour}:00 - ${summary.peakHour + 1}:00

---
Auto-generated by 9Yards Kitchen`;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Get date from request or use yesterday
    const { date } = await req.json().catch(() => ({}));
    const summaryDate = date ? new Date(date) : new Date(Date.now() - 24 * 60 * 60 * 1000);

    // Generate summary
    const summary = await generateDailySummary(supabase, summaryDate);
    const message = formatSummaryMessage(summary);

    // Send via WhatsApp if configured
    const whatsappNumber = Deno.env.get("ADMIN_WHATSAPP_NUMBER");
    const whatsappApiKey = Deno.env.get("WHATSAPP_API_KEY");

    if (whatsappNumber && whatsappApiKey) {
      try {
        // Send WhatsApp message (example with WhatsApp Business API)
        const response = await fetch("https://graph.facebook.com/v17.0/YOUR_PHONE_NUMBER_ID/messages", {
          method: "POST",
          headers: {
            "Authorization": `Bearer ${whatsappApiKey}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            messaging_product: "whatsapp",
            to: whatsappNumber,
            type: "text",
            text: { body: message },
          }),
        });

        if (!response.ok) {
          console.error("WhatsApp send failed:", await response.text());
        }
      } catch (err) {
        console.error("WhatsApp error:", err);
      }
    }

    // Also create a notification in the database
    await supabase.from("notifications").insert({
      title: "Daily Sales Summary",
      message: `Revenue: UGX ${summary.totalRevenue.toLocaleString()}, Orders: ${summary.totalOrders}`,
      type: "analytics",
      data: summary,
    });

    return new Response(
      JSON.stringify({ success: true, summary, message }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Daily summary error:", error);
    return new Response(
      JSON.stringify({ error: "Failed to generate summary" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
