-- 003: Create orders table
create type public.order_status as enum ('new', 'preparing', 'ready', 'delivered', 'cancelled');
create type public.payment_method as enum ('cash', 'mobile_money', 'pay_at_counter');
create type public.payment_status as enum ('pending', 'paid', 'failed');

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text unique, -- auto-generated by trigger
  status public.order_status not null default 'new',
  customer_name text not null,
  customer_phone text,
  customer_location text,
  payment_method public.payment_method not null default 'pay_at_counter',
  payment_status public.payment_status not null default 'pending',
  momo_transaction_id text,
  subtotal int not null default 0,
  total int not null default 0,
  special_instructions text,
  source text not null default 'kiosk',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  prepared_at timestamptz,
  ready_at timestamptz,
  delivered_at timestamptz
);

create index idx_orders_status on public.orders(status);
create index idx_orders_created on public.orders(created_at desc);

alter table public.orders enable row level security;
